[server]
port = 12312
name = "asdasd"
version = "1.0.0"
route-prefix = ""


[log]
log-dir = ""
level = "info"
type = "std,file"
file-size-mb = 1
retention-days = 15

[sys_mysql]
host = "127.0.0.1"
user = "root"
password = "123456"
database = "play_v1"

[transport]
server-port = 12313
client-port = 12314
